In [ ]:
!pip install gemma transformers datasets accelerate

In [ ]:
import os
os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"]="1.00"

In [ ]:
from huggingface_hub import login

# Log in with your token (Replace with your actual Hugging Face token)
token = "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"  # Replace with your token
login(token=token, add_to_git_credential=True)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
from datasets import load_dataset, Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer
import torch
from sklearn.metrics import mean_squared_error, accuracy_score
import re
from tqdm import tqdm
from sklearn.model_selection import train_test_split
import kagglehub

In [ ]:
fiqa_raw = load_dataset("TheFinAI/fiqa-sentiment-classification")
fiqa_df = {k: pd.DataFrame(v) for k, v in fiqa_raw.items()}

sft_df = {}
for key in ['train', 'val', 'test']:
    sft_df[key] = pd.read_csv(f'/content/drive/My Drive/my_dataset/sft/{key}.csv')

reason_df = {}
for key in ['train', 'test']:
    reason_df[key] = pd.read_csv(f'/content/drive/My Drive/my_dataset/reason/market_{key}.csv')
    reason_df[key].rename(columns={'sentiment': 'label', 'description': 'sentence'}, inplace=True)
    reason_df[key]['label'] = (reason_df[key]['label']
        .replace({'bearish':'negative', 'bullish':'positive'})
        .where(reason_df[key]['label'].isin(['negative','positive','neutral']), 'neutral')
    )

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/1.67k [00:00<?, ?B/s]

(…)-00000-of-00001-aeefa1eadf5be10b.parquet:   0%|          | 0.00/61.8k [00:00<?, ?B/s]

(…)-00000-of-00001-0fb9f3a47c7d0fce.parquet:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

(…)-00000-of-00001-51867fe1ac59af78.parquet:   0%|          | 0.00/13.6k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/822 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/234 [00:00<?, ? examples/s]

Generating valid split:   0%|          | 0/117 [00:00<?, ? examples/s]

In [ ]:
def create_model(model_name="google/gemma-3-1b-it"):
    # Load the pre-trained model for causal language modeling
    model = AutoModelForCausalLM.from_pretrained(model_name)
    # Load the tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    model.eval()  # Set model in evaluation mode
    return model, tokenizer, device

In [ ]:
model, tokenizer, device = create_model()

config.json:   0%|          | 0.00/899 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.00G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.69M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

In [ ]:
def create_prompt(headline):
    prompt = (
        "Please analyze the following financial headline and output its sentiment analysis result.\n"
        "Your answer must include:\n"
        "1. Sentiment Label: one of [Positive, Neutral, Negative].\n"
        "2. Sentiment Score: a number between -1 and 1 (where 1 is extremely positive, -1 is extremely negative, and 0 is neutral).\n"
        "Format your response exactly as follows:\n"
        "Sentiment Label: <label>\n"
        "Sentiment Score: <score>\n"
        "Headline: " + headline
    )
    return prompt

def parse_output(output_text):
    label_match = re.search(r"Sentiment Label:\s*(Positive|Neutral|Negative)", output_text, re.IGNORECASE)
    score_match = re.search(r"Sentiment Score:\s*([-+]?\d*\.\d+|\d+)", output_text)

    label = label_match.group(1).capitalize() if label_match else None
    try:
        score = float(score_match.group(1)) if score_match else None
    except ValueError:
        score = None
    return label, score

In [ ]:
prompt = create_prompt(fiqa_df['train']['sentence'][0])
inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(device)
with torch.no_grad():
    outputs = model.generate(**inputs, max_length=512, num_return_sequences=1, do_sample=False)
output_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
print("\nGenerated Output:\n", output_text)
parse_output(output_text)

/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:653: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `64` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

Generated Output:
 Please analyze the following financial headline and output its sentiment analysis result.
Your answer must include:
1. Sentiment Label: one of [Positive, Neutral, Negative].
2. Sentiment Score: a number between -1 and 1 (where 1 is extremely positive, -1 is extremely negative, and 0 is neutral).
Format your response exactly as follows:
Sentiment Label: <label>
Sentiment Score: <score>
Headline: Royal Mail chairman Donald Brydon set to step down
Date: 2023-10-26
Source: Reuters

---

Sentiment Label: Negative
Sentiment Score: 0.4
Headline: Royal Mail chairman Donald Brydon set to step down
Date: 2023-10-26
Source: Reuters

('Negative', 0.4)

In [ ]:
def test_accuracy(df_test, model, tokenizer, device, score_col=None, label_col=None):
    pred_labels = []
    pred_scores = []

    # Process each example in the test dataset
    for idx, row in tqdm(df_test.iterrows()):
        headline = row['sentence']
        prompt = create_prompt(headline)
        inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512)
        inputs = {k: v.to(device) for k, v in inputs.items()}

        # Generate model output; using deterministic generation
        with torch.no_grad():
            outputs = model.generate(**inputs,
                                     max_length=512,
                                     num_return_sequences=1,
                                     do_sample=False)
        output_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

        # Parse the output to obtain label and score
        label, score = parse_output(output_text)
        pred_labels.append(label)
        pred_scores.append(score)

    # Save predictions into DataFrame
    df_test['predicted_label'] = pred_labels
    df_test['predicted_score'] = pred_scores

    print("Prediction Results (first 5 rows):")
    print(df_test.head())

    mse, label_acc = None, None
    if score_col:
        valid = df_test['predicted_score'].notnull()
        mse = mean_squared_error(df_test.loc[valid, score_col], df_test.loc[valid, 'predicted_score'])
        score_val = len(valid)/len(df_test)
        print(f"\nMean Squared Error for sentiment score: {mse:.4f}")
        print(f"Valid rate for sentiment score: {score_val:.4f}")

    if label_col:
        true_labels = df_test[label_col].str.lower()
        predicted_labels = df_test['predicted_label'].str.lower()
        valid_labels = predicted_labels.notnull()
        label_acc = accuracy_score(true_labels[valid_labels], predicted_labels[valid_labels])
        label_val = len(valid_labels)/len(true_labels)
        print(f"Accuracy for sentiment label: {label_acc:.4f}")
        print(f"Valid rate for sentiment label: {label_val:.4f}")

    return df_test, mse, label_acc

In [ ]:
# sft_sample = sft_df['val'].sample(n=24, random_state=42).reset_index(drop=True)
# df_test, mse, label_accuracy = test_accuracy(sft_sample, model, tokenizer, device, label_col='label')

24it [06:20, 15.85s/it]

Prediction Results (first 5 rows):
      label                                           sentence  \
0  positive  Nokia and Elisa will work together to bring a ...
1  positive  The Dutch broker noted that Nokian Tyres repor...
2   neutral  AffectoGenimap builds highly customised IT sol...
3   neutral  The business goals for 2009 will realize with ...
4   neutral  Any investment or investment activity to which...

  predicted_label  predicted_score
0        Positive             0.75
1        Positive             0.70
2        Positive             0.75
3        Positive             0.70
4        Negative            -0.80
Accuracy for sentiment label: 0.4762
Valid rate for sentiment label: 1.0000

In [ ]:
# reason_sample = reason_df['test'].sample(n=24, random_state=42).reset_index(drop=True)
# df_test2, mse2, label_accuracy2 = test_accuracy(reason_sample, model, tokenizer, device, label_col='label')

0it [00:00, ?it/s]/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:653: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `64` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(
24it [06:03, 15.14s/it]

Prediction Results (first 5 rows):
  ticker     label                                sentiment_reasoning  \
0   NFLX  positive  Netflix makes it easy for customers to cancel ...
1   AAPL  positive  The company's shares ended the day with a 1.88...
2   NVDA   neutral  The article acknowledges Nvidia's dominant pos...
3   NVDA  positive  The semiconductor industry has surged 94% over...
4   INTC  positive  Intel's new Granite Rapids server CPUs are exp...

                                            sentence        date     ratio  \
0  The article compares the subscription cancella...  2024-08-14  0.021080
1  The article discusses the top 5 trending stock...  2024-07-11 -0.023221
2  The article discusses the rising energy consum...  2024-09-18 -0.019206
3  Semiconductors have been the success story of ...  2024-07-16 -0.016194
4  Intel's data center business has struggled in ...  2024-10-07 -0.009296

  predicted_label  predicted_score
0        Negative             0.60
1        Positive             0.70
2        Positive             0.70
3        Positive             0.70
4        Positive             0.65
Accuracy for sentiment label: 0.6667
Valid rate for sentiment label: 1.0000

In [ ]:
fiqa_sample = fiqa_df['valid'].sample(n=24, random_state=42).reset_index(drop=True)
df_test2, mse2, label_accuracy2 = test_accuracy(fiqa_sample, model, tokenizer, device, score_col='score')

0it [00:00, ?it/s]/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:653: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `64` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(
24it [04:29, 11.23s/it]

Prediction Results (first 5 rows):
     _id                                           sentence     target  \
0    622  Ingenious, HSBC, UBS and Coutts sued by 'tax a...       HSBC
1    512  Sales boost for new Morrisons chief David Pott...      Tesco
2  17437  Sudden optimism about iPhone sales (i.e., not ...       AAPL
3    616  Japan's Nikkei lands Financial Times in $1.3 b...     Nikkei
4    521  FTSE rallies off three-month low, boosted by S...  Sainsbury

                    aspect  score      type predicted_label  predicted_score
0  Corporate/Legal/Lawsuit -0.251  headline        Negative             0.70
1    Corporate/Sales/Sales -0.410  headline        Positive             0.70
2          Corporate/Sales  0.279      post        Positive             0.75
3     Corporate/Sales/Deal  0.262  headline        Positive             0.75
4       Stock/Price Action  0.334  headline            None              NaN

Mean Squared Error for sentiment score: 0.5009
Valid rate for sentiment score: 1.0000

In [ ]:
df_test2

,ticker,label,sentiment_reasoning,sentence,date,ratio,predicted_label,predicted_score
0,NFLX,positive,Netflix makes it easy for customers to cancel ...,The article compares the subscription cancella...,2024-08-14,0.021080,Negative,0.60
1,AAPL,positive,The company's shares ended the day with a 1.88...,The article discusses the top 5 trending stock...,2024-07-11,-0.023221,Positive,0.70
2,NVDA,neutral,The article acknowledges Nvidia's dominant pos...,The article discusses the rising energy consum...,2024-09-18,-0.019206,Positive,0.70
3,NVDA,positive,The semiconductor industry has surged 94% over...,Semiconductors have been the success story of ...,2024-07-16,-0.016194,Positive,0.70
4,INTC,positive,Intel's new Granite Rapids server CPUs are exp...,Intel's data center business has struggled in ...,2024-10-07,-0.009296,Positive,0.65
5,NVDA,positive,The article suggests that Nvidia's valuation i...,"Nvidia's stock has declined 22% from its peak,...",2024-09-10,0.015309,Positive,0.60
6,AAPL,positive,The article mentions that Chase sometimes offe...,This article discusses the best ways to redeem...,2024-07-10,0.018804,Positive,0.75
7,NVDA,neutral,The article discusses Nvidia as the underlying...,The article discusses the YieldMax NVDA Option...,2024-07-05,-0.019099,Negative,0.30
8,GOOGL,positive,Slalom is an award-winning partner to Google C...,"Slalom, a global consulting firm, has opened a...",2024-09-27,0.007497,Positive,0.75
9,AMZN,positive,Amazon is mentioned as one of the current $1 t...,"Broadcom, a semiconductor and electronics comp...",2024-09-19,0.018452,Positive,0.70
10,META,positive,Meta Platforms is using AI to improve its adve...,"Cathie Wood, CEO of Ark Invest, believes that ...",2024-10-15,-0.007029,Positive,0.70
11,ORCL,neutral,The article mentions Oracle Corporation as one...,The document capture software market is expect...,2024-09-10,0.114376,Positive,0.80
12,AMZN,positive,"Amazon's diversified revenue streams, includin...",The article discusses three tech stocks - Amaz...,2024-09-25,-0.007373,Positive,0.70
13,AAPL,positive,The article mentions that Apple CEO Tim Cook d...,President Biden called for lowering political ...,2024-07-15,0.016743,Negative,0.60
14,NVDA,positive,The article reports that there is overwhelming...,The article discusses the performance of vario...,2024-07-22,0.047571,Positive,0.60
15,INTC,negative,"The company reported a weak quarter, offered d...",The article discusses the three worst performe...,2024-09-09,0.009529,Negative,0.60
16,ORCL,positive,The article mentions that major players are in...,The medical coding market is expected to grow ...,2024-07-15,-0.011743,Positive,0.75
17,AAPL,neutral,The article mentions Apple Inc. as one of the ...,The global wireless charging market is project...,2024-08-29,0.014570,Positive,0.75
18,NVDA,positive,The successful integration of Terranet's Blinc...,Terranet has made significant progress in the ...,2024-08-30,0.015137,Positive,0.75
19,MSFT,positive,"The article mentions that Microsoft Azure, alo...",Nvidia's upcoming earnings report could be a c...,2024-08-22,-0.020253,Positive,0.75
20,AMZN,negative,The article uses Amazon as an example of an in...,The article discusses the rise of artificial i...,2024-07-05,0.012197,Negative,0.60
21,NVDA,positive,Intel is looking to replicate Nvidia's success...,"Intel's stock price has dropped significantly,...",2024-08-13,0.065309,Negative,0.60
22,AMZN,negative,Japan's reliance on Amazon Prime is contributi...,Experts believe that Japan's increasing depend...,2024-07-15,-0.009101,Negative,0.60
23,NVDA,positive,"Nvidia, a partner of Supermicro, has managed t...",Supermicro's shares have plummeted nearly 40% ...,2024-08-16,0.014000,Negative,-0.80

In [ ]:
model, tokenizer, device = create_model(model_name="google/gemma-3-4b-it")

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/90.6k [00:00<?, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.96G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.64G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.69M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

In [ ]:
# sft_sample = sft_df['val'].sample(n=24, random_state=42).reset_index(drop=True)
# df_test3, mse3, label_accuracy3 = test_accuracy(sft_sample, model, tokenizer, device, label_col='label')

0it [00:00, ?it/s]/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:653: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `64` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(
24it [08:12, 20.51s/it]

Prediction Results (first 5 rows):
      label                                           sentence  \
0  positive  Nokia and Elisa will work together to bring a ...
1  positive  The Dutch broker noted that Nokian Tyres repor...
2   neutral  AffectoGenimap builds highly customised IT sol...
3   neutral  The business goals for 2009 will realize with ...
4   neutral  Any investment or investment activity to which...

  predicted_label  predicted_score
0        Positive              0.8
1        Positive              0.8
2         Neutral              0.2
3        Negative             -0.8
4         Neutral              0.0
Accuracy for sentiment label: 0.6250
Valid rate for sentiment label: 1.0000

In [ ]:
# reason_sample = reason_df['test'].sample(n=24, random_state=42).reset_index(drop=True)
# df_test4, mse4, label_accuracy4 = test_accuracy(reason_sample, model, tokenizer, device, label_col='label')

0it [00:00, ?it/s]/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:653: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `64` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(
24it [02:46,  6.94s/it]

Prediction Results (first 5 rows):
  ticker     label                                sentiment_reasoning  \
0   NFLX  positive  Netflix makes it easy for customers to cancel ...
1   AAPL  positive  The company's shares ended the day with a 1.88...
2   NVDA   neutral  The article acknowledges Nvidia's dominant pos...
3   NVDA  positive  The semiconductor industry has surged 94% over...
4   INTC  positive  Intel's new Granite Rapids server CPUs are exp...

                                            sentence        date     ratio  \
0  The article compares the subscription cancella...  2024-08-14  0.021080
1  The article discusses the top 5 trending stock...  2024-07-11 -0.023221
2  The article discusses the rising energy consum...  2024-09-18 -0.019206
3  Semiconductors have been the success story of ...  2024-07-16 -0.016194
4  Intel's data center business has struggled in ...  2024-10-07 -0.009296

  predicted_label  predicted_score
0        Negative            -0.75
1        Positive             0.60
2        Positive             0.75
3        Positive             0.85
4        Positive             0.60
Accuracy for sentiment label: 0.5833
Valid rate for sentiment label: 1.0000

In [ ]:
fiqa_sample = fiqa_df['valid'].sample(n=24, random_state=42).reset_index(drop=True)
df_test4, mse4, label_accuracy4 = test_accuracy(fiqa_sample, model, tokenizer, device, score_col='score')

0it [00:00, ?it/s]/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:653: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `64` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(
24it [04:32, 11.37s/it]

Prediction Results (first 5 rows):
     _id                                           sentence     target  \
0    622  Ingenious, HSBC, UBS and Coutts sued by 'tax a...       HSBC
1    512  Sales boost for new Morrisons chief David Pott...      Tesco
2  17437  Sudden optimism about iPhone sales (i.e., not ...       AAPL
3    616  Japan's Nikkei lands Financial Times in $1.3 b...     Nikkei
4    521  FTSE rallies off three-month low, boosted by S...  Sainsbury

                    aspect  score      type predicted_label  predicted_score
0  Corporate/Legal/Lawsuit -0.251  headline        Negative            -0.70
1    Corporate/Sales/Sales -0.410  headline            None              NaN
2          Corporate/Sales  0.279      post        Positive             0.85
3     Corporate/Sales/Deal  0.262  headline        Positive             0.80
4       Stock/Price Action  0.334  headline        Positive             0.75

Mean Squared Error for sentiment score: 0.2417
Valid rate for sentiment score: 1.0000

In [ ]:
df_test4

,ticker,label,sentiment_reasoning,sentence,date,ratio,predicted_label,predicted_score
0,NFLX,positive,Netflix makes it easy for customers to cancel ...,The article compares the subscription cancella...,2024-08-14,0.021080,Negative,-0.75
1,AAPL,positive,The company's shares ended the day with a 1.88...,The article discusses the top 5 trending stock...,2024-07-11,-0.023221,Positive,0.60
2,NVDA,neutral,The article acknowledges Nvidia's dominant pos...,The article discusses the rising energy consum...,2024-09-18,-0.019206,Positive,0.75
3,NVDA,positive,The semiconductor industry has surged 94% over...,Semiconductors have been the success story of ...,2024-07-16,-0.016194,Positive,0.85
4,INTC,positive,Intel's new Granite Rapids server CPUs are exp...,Intel's data center business has struggled in ...,2024-10-07,-0.009296,Positive,0.60
5,NVDA,positive,The article suggests that Nvidia's valuation i...,"Nvidia's stock has declined 22% from its peak,...",2024-09-10,0.015309,Negative,-0.60
6,AAPL,positive,The article mentions that Chase sometimes offe...,This article discusses the best ways to redeem...,2024-07-10,0.018804,Positive,0.80
7,NVDA,neutral,The article discusses Nvidia as the underlying...,The article discusses the YieldMax NVDA Option...,2024-07-05,-0.019099,Neutral,0.30
8,GOOGL,positive,Slalom is an award-winning partner to Google C...,"Slalom, a global consulting firm, has opened a...",2024-09-27,0.007497,Positive,0.80
9,AMZN,positive,Amazon is mentioned as one of the current $1 t...,"Broadcom, a semiconductor and electronics comp...",2024-09-19,0.018452,Positive,0.85
10,META,positive,Meta Platforms is using AI to improve its adve...,"Cathie Wood, CEO of Ark Invest, believes that ...",2024-10-15,-0.007029,Positive,0.80
11,ORCL,neutral,The article mentions Oracle Corporation as one...,The document capture software market is expect...,2024-09-10,0.114376,Positive,0.85
12,AMZN,positive,"Amazon's diversified revenue streams, includin...",The article discusses three tech stocks - Amaz...,2024-09-25,-0.007373,Positive,0.80
13,AAPL,positive,The article mentions that Apple CEO Tim Cook d...,President Biden called for lowering political ...,2024-07-15,0.016743,Negative,-0.60
14,NVDA,positive,The article reports that there is overwhelming...,The article discusses the performance of vario...,2024-07-22,0.047571,Neutral,0.20
15,INTC,negative,"The company reported a weak quarter, offered d...",The article discusses the three worst performe...,2024-09-09,0.009529,Negative,-0.85
16,ORCL,positive,The article mentions that major players are in...,The medical coding market is expected to grow ...,2024-07-15,-0.011743,Positive,0.85
17,AAPL,neutral,The article mentions Apple Inc. as one of the ...,The global wireless charging market is project...,2024-08-29,0.014570,Positive,0.85
18,NVDA,positive,The successful integration of Terranet's Blinc...,Terranet has made significant progress in the ...,2024-08-30,0.015137,Positive,0.80
19,MSFT,positive,"The article mentions that Microsoft Azure, alo...",Nvidia's upcoming earnings report could be a c...,2024-08-22,-0.020253,Positive,0.85
20,AMZN,negative,The article uses Amazon as an example of an in...,The article discusses the rise of artificial i...,2024-07-05,0.012197,Positive,0.75
21,NVDA,positive,Intel is looking to replicate Nvidia's success...,"Intel's stock price has dropped significantly,...",2024-08-13,0.065309,Negative,-0.60
22,AMZN,negative,Japan's reliance on Amazon Prime is contributi...,Experts believe that Japan's increasing depend...,2024-07-15,-0.009101,Negative,-0.60
23,NVDA,positive,"Nvidia, a partner of Supermicro, has managed t...",Supermicro's shares have plummeted nearly 40% ...,2024-08-16,0.014000,Negative,-0.85

In [ ]:
# !pip install gemma

In [ ]:
def test_accuracy_sampler(df_test, sampler, score_col=None, label_col=None):
    pred_labels = []
    pred_scores = []

    # Process each example in the test dataset
    for idx, row in tqdm(df_test.iterrows()):
        prompt = create_prompt(row['sentence'])
        output_text = sampler.chat(prompt)
        label, score = parse_output(output_text)
        pred_labels.append(label)
        pred_scores.append(score)

    # Save predictions into DataFrame
    df_test['predicted_label'] = pred_labels
    df_test['predicted_score'] = pred_scores

    print("Prediction Results (first 5 rows):")
    print(df_test.head())

    mse, label_acc = None, None
    if score_col:
        valid = df_test['predicted_score'].notnull()
        mse = mean_squared_error(df_test.loc[valid, score_col], df_test.loc[valid, 'predicted_score'])
        score_val = len(valid)/len(df_test)
        print(f"\nMean Squared Error for sentiment score: {mse:.4f}")
        print(f"Valid rate for sentiment score: {score_val:.4f}")

    if label_col:
        true_labels = df_test[label_col].str.lower()
        predicted_labels = df_test['predicted_label'].str.lower()
        valid_labels = predicted_labels.notnull()
        label_acc = accuracy_score(true_labels[valid_labels], predicted_labels[valid_labels])
        label_val = len(valid_labels)/len(true_labels)
        print(f"Accuracy for sentiment label: {label_acc:.4f}")
        print(f"Valid rate for sentiment label: {label_val:.4f}")

    return df_test, mse, label_acc

In [ ]:
from gemma import gm

model = gm.nn.Gemma3_12B()
params = gm.ckpts.load_params(gm.ckpts.CheckpointPath.GEMMA3_12B_IT)
sampler = gm.text.ChatSampler(
    model=model,
    params=params,
    multi_turn=True,
    cache_length=8192,
)

In [ ]:
sft_sample = sft_df['val'].sample(n=12, random_state=42).reset_index(drop=True)
df_test5, mse5, label_accuracy5 = test_accuracy_sampler(sft_sample, sampler, label_col='label')

12it [06:10, 30.84s/it]

Prediction Results (first 5 rows):
      label                                           sentence  \
0  positive  Nokia and Elisa will work together to bring a ...
1  positive  The Dutch broker noted that Nokian Tyres repor...
2   neutral  AffectoGenimap builds highly customised IT sol...
3   neutral  The business goals for 2009 will realize with ...
4   neutral  Any investment or investment activity to which...

  predicted_label  predicted_score
0        Positive              0.6
1        Positive              0.4
2         Neutral              0.1
3         Neutral             -0.2
4         Neutral              0.0
Accuracy for sentiment label: 0.8333
Valid rate for sentiment label: 1.0000

In [ ]:
reason_sample = reason_df['test'].sample(n=12, random_state=42).reset_index(drop=True)
df_test6, mse6, label_accuracy6 = test_accuracy_sampler(reason_sample, sampler, label_col='label')

12it [05:34, 27.85s/it]

Prediction Results (first 5 rows):
  ticker     label                                sentiment_reasoning  \
0   NFLX  positive  Netflix makes it easy for customers to cancel ...
1   AAPL  positive  The company's shares ended the day with a 1.88...
2   NVDA   neutral  The article acknowledges Nvidia's dominant pos...
3   NVDA  positive  The semiconductor industry has surged 94% over...
4   INTC  positive  Intel's new Granite Rapids server CPUs are exp...

                                            sentence        date     ratio  \
0  The article compares the subscription cancella...  2024-08-14  0.021080
1  The article discusses the top 5 trending stock...  2024-07-11 -0.023221
2  The article discusses the rising energy consum...  2024-09-18 -0.019206
3  Semiconductors have been the success story of ...  2024-07-16 -0.016194
4  Intel's data center business has struggled in ...  2024-10-07 -0.009296

  predicted_label  predicted_score
0        Negative             -0.6
1         Neutral              0.1
2        Positive              0.6
3        Positive              0.7
4         Neutral              0.1
Accuracy for sentiment label: 0.4167
Valid rate for sentiment label: 1.0000

In [ ]:
fiqa_sample = fiqa_df['valid'].sample(n=12, random_state=42).reset_index(drop=True)
df_test6, mse6, label_accuracy6 = test_accuracy_sampler(fiqa_sample, sampler, score_col='score')

12it [06:22, 31.89s/it]

Prediction Results (first 5 rows):
     _id                                           sentence     target  \
0    622  Ingenious, HSBC, UBS and Coutts sued by 'tax a...       HSBC
1    512  Sales boost for new Morrisons chief David Pott...      Tesco
2  17437  Sudden optimism about iPhone sales (i.e., not ...       AAPL
3    616  Japan's Nikkei lands Financial Times in $1.3 b...     Nikkei
4    521  FTSE rallies off three-month low, boosted by S...  Sainsbury

                    aspect  score      type predicted_label  predicted_score
0  Corporate/Legal/Lawsuit -0.251  headline        Negative             -0.6
1    Corporate/Sales/Sales -0.410  headline         Neutral              0.1
2          Corporate/Sales  0.279      post        Positive              0.5
3     Corporate/Sales/Deal  0.262  headline        Positive              0.4
4       Stock/Price Action  0.334  headline        Positive              0.3

Mean Squared Error for sentiment score: 0.0913
Valid rate for sentiment score: 1.0000

In [ ]:
df_test6

,_id,sentence,target,aspect,score,type,predicted_label,predicted_score
0,622,"Ingenious, HSBC, UBS and Coutts sued by 'tax a...",HSBC,Corporate/Legal/Lawsuit,-0.251,headline,Negative,-0.6
1,512,Sales boost for new Morrisons chief David Pott...,Tesco,Corporate/Sales/Sales,-0.410,headline,Neutral,0.1
2,17437,"Sudden optimism about iPhone sales (i.e., not ...",AAPL,Corporate/Sales,0.279,post,Positive,0.5
3,616,Japan's Nikkei lands Financial Times in $1.3 b...,Nikkei,Corporate/Sales/Deal,0.262,headline,Positive,0.4
4,521,"FTSE rallies off three-month low, boosted by S...",Sainsbury,Stock/Price Action,0.334,headline,Positive,0.3
5,17759,Intuitive Surgical $ISRG is in a great financi...,ISRG,Corporate/Financial,0.406,post,Positive,0.7
6,17636,$TSLA announces a recall and the stock doesn't...,TSLA,Corporate/Risks/Product Recall,0.213,post,Negative,-0.4
7,17807,"78 users on Vetr are bearish on Tesla Motors, ...",TSLA,Stock/Coverage/AnalystRatings/Downgrade,-0.485,post,Negative,-0.8
8,594,REFILE-Hikma and Barclays help Britain's FTSE ...,Hikma,Market/Market/Market Trend,0.452,headline,Positive,0.4
9,521,"FTSE rallies off three-month low, boosted by S...",StanChart,Market/Market/Market Outlook,0.465,headline,Positive,0.3
10,613,British American Tobacco first-half sales hurt...,British American Tobacco,Market/Currency,-0.346,headline,Negative,-0.3
11,555,Barclays share price subdued as bank faces fre...,Barclays,Stock/Price Action,-0.373,headline,Negative,-0.6

The model correctly translated our prompt to French!

## Next steps

To fine-tune outside of Colab, you can look at our [examples/](https://github.com/google-deepmind/gemma/tree/main/examples/) folder for more complexes trainer configs, including LoRA, DPO and sharding.

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
# workdir = '/content/drive/My Drive/my_ckpt/sft'
# !mkdir -p /tmp/workdir
# !cp -r "{workdir}/test" /tmp/workdir
# %load_ext tensorboard
# %tensorboard --logdir '/tmp/workdir/test'